import { useState } from "react";
import { jsPDF } from "jspdf";

function TodoItem({ todo, onToggle, onDelete, onEdit }) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedTitle, setEditedTitle] = useState(todo.title);
  const [editedDesc, setEditedDesc] = useState(todo.description || '');

  const handleToggleStatus = () => {
    onToggle(todo._id, { completed: !todo.completed });
  };
  const saveChanges = () => {
    if (!editedTitle.trim()) return;
    onEdit(todo._id, {
      title: editedTitle.trim(),
      description: editedDesc.trim()
    });
    setIsEditing(false);
  };

  const downloadTask = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("Task Details", 20, 20);

    doc.setFontSize(16);
    doc.setTextColor(60, 60, 60);
    doc.text(`Title: ${todo.title}`, 20, 40);

    doc.setFontSize(12);
    doc.text(`Status: ${todo.completed ? "Completed" : "Pending"}`, 20, 55);

    if (todo.startDate) {
      doc.text(`Start Date: ${new Date(todo.startDate).toLocaleDateString()}`, 20, 65);
    }

    if (todo.deadline) {
      doc.text(`Deadline: ${new Date(todo.deadline).toLocaleDateString()}`, 20, 75);
    }

    if (todo.description) {
      doc.text("Description:", 20, 90);
      const splitDesc = doc.splitTextToSize(todo.description, 170);
      doc.text(splitDesc, 20, 100);
    }

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Task Master App", 20, 280);

    doc.save(`task-${todo.title.replace(/\s+/g, '-').toLowerCase()}.pdf`);
  };

  const formatDate = (dateString) => {
    if (!dateString) return null;
    return new Date(dateString).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
  };

  return (
    <div className={`glass-card p-5 flex flex-col h-full group transition-all duration-300 ${todo.completed ? 'opacity-80' : ''}`}>

      {/* Header */}
      <div className="flex items-start gap-3 mb-3">
        <input
          type="checkbox"
          checked={todo.completed}
          onChange={handleToggleStatus}
          className="mt-1.5 w-5 h-5 rounded border-slate-600 text-indigo-500 focus:ring-indigo-500 bg-slate-700/50 cursor-pointer"
        />

        <div className="w-full">
          {isEditing ? (
            <div className="space-y-2">
              <input
                value={editedTitle}
                onChange={(e) => setEditedTitle(e.target.value)}
                className="w-full bg-slate-700/50 text-slate-100 p-2 rounded border border-slate-600 focus:ring-2 focus:ring-indigo-500 outline-none font-medium"
                autoFocus
              />
              <textarea
                value={editedDesc}
                onChange={(e) => setEditedDesc(e.target.value)}
                className="w-full bg-slate-700/50 text-slate-100 p-2 rounded border border-slate-600 focus:ring-2 focus:ring-indigo-500 outline-none text-sm resize-none"
                rows="2"
                placeholder="Description..."
              />
            </div>
          ) : (
            <div>
              <h3 className={`text-lg font-semibold text-white break-words leading-tight ${todo.completed ? 'line-through text-slate-400' : ''}`}>
                {todo.title}
              </h3>
              {todo.description && (
                <p className={`text-sm text-slate-200 mt-1 break-words ${todo.completed ? 'line-through opacity-70' : ''}`}>
                  {todo.description}
                </p>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Dates */}
      {!isEditing && (todo.startDate || todo.deadline) && (
        <div className="flex flex-wrap gap-2 mt-2 mb-4 text-xs font-medium">
          {todo.startDate && (
            <span className="bg-indigo-500/10 text-indigo-300 px-2 py-1 rounded border border-indigo-500/20">
              Start: {formatDate(todo.startDate)}
            </span>
          )}
          {todo.deadline && (
            <span className="bg-pink-500/10 text-pink-300 px-2 py-1 rounded border border-pink-500/20">
              Due: {formatDate(todo.deadline)}
            </span>
          )}
        </div>
      )}

      {/* Footer */}
      <div className="mt-auto pt-4 border-t border-slate-700/30 flex items-center justify-between gap-2 opacity-0 group-hover:opacity-100 transition-opacity duration-200">

        {todo.completed && !isEditing && (
          <button
            onClick={downloadTask}
            className="text-xs flex items-center gap-1 text-emerald-400 hover:text-emerald-300 transition-colors"
            title="Download PDF"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            PDF
          </button>
        )}

        <div className="flex gap-2 ml-auto">
          {isEditing ? (
            <>
              <button onClick={saveChanges} className="btn btn-primary text-xs py-1 px-3">Save</button>
              <button onClick={() => setIsEditing(false)} className="btn btn-secondary text-xs py-1 px-3">Cancel</button>
            </>
          ) : (
            <>
              <button onClick={() => setIsEditing(true)} className="text-xs text-slate-200 hover:text-white transition-colors">Edit</button>
              <button onClick={() => onDelete(todo._id)} className="text-xs text-red-400 hover:text-red-300 transition-colors">Delete</button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

export default TodoItem;
